"""Compatibility manifest for the documented public API."""

from __future__ import annotations

PUBLIC_EXPORTS: dict[str, set[str]] = {
    "torch_batteries": {
        "BatchScheduleConfig",
        "Battery",
        "CollectedMetric",
        "DataContext",
        "DataLoaderBundle",
        "DataLoaderConfig",
        "DataPack",
        "DataPackHandler",
        "DatasetBundle",
        "Event",
        "EventContext",
        "FitResult",
        "MetricSpec",
        "OptimizationStep",
        "PredictResult",
        "ResolvedData",
        "Run",
        "StatefulMetric",
        "StepOutput",
        "TestResult",
        "TrainResult",
        "ValidationResult",
        "charge",
    },
    "torch_batteries.callbacks": {
        "Callback",
        "EarlyStopping",
        "ExperimentTrackingCallback",
        "GradientAccumulation",
        "GradientClip",
        "LearningRateScheduler",
        "MixedPrecision",
        "ModelCheckpoint",
        "TerminateOnNonFinite",
    },
    "torch_batteries.data": {
        "BatchScheduleConfig",
        "DataContext",
        "DataLoaderBundle",
        "DataLoaderConfig",
        "DataPack",
        "DataPackHandler",
        "DatasetBundle",
        "ResolvedData",
    },
    "torch_batteries.events": {
        "Event",
        "EventContext",
        "EventHandler",
        "OptimizationStep",
        "charge",
    },
    "torch_batteries.tracking": {"ExperimentTracker", "Run", "WandbTracker"},
    "torch_batteries.trainer": {
        "Battery",
        "FitResult",
        "PredictResult",
        "StepOutput",
        "TestResult",
        "TrainResult",
        "ValidationResult",
    },
    "torch_batteries.utils.metrics": {
        "CollectedMetric",
        "Metric",
        "MetricCallable",
        "MetricSpec",
        "PhaseMetricManager",
        "StatefulMetric",
        "calculate_metrics",
    },
}

PUBLIC_MEMBERS: dict[str, set[str]] = {
    "torch_batteries.trainer.Battery": {
        "model",
        "device",
        "data_pack",
        "optimizer",
        "metrics",
        "metric_error_policy",
        "stop_training",
        "save_checkpoint",
        "load_checkpoint",
        "train",
        "fit",
        "validate",
        "test",
        "predict",
        "predict_iter",
    },
    "torch_batteries.callbacks.Callback": {"state_dict", "load_state_dict"},
    "torch_batteries.callbacks.EarlyStopping": {
        "best_score",
        "best_weights",
        "state_dict",
        "load_state_dict",
        "run_on_train_start",
        "run_on_epoch_end",
        "run_on_validation_end",
        "run_on_train_end",
    },
    "torch_batteries.callbacks.ExperimentTrackingCallback": {
        "tracker",
        "run",
        "global_step",
        "current_epoch",
        "log_every_n_steps",
        "state_dict",
        "load_state_dict",
        "on_train_start",
        "on_epoch_start",
        "on_train_step_end",
        "on_validation_epoch_end",
        "on_train_end",
        "on_exception",
    },
    "torch_batteries.callbacks.GradientAccumulation": {
        "steps",
        "optimizer_step_idx",
        "reset",
        "is_group_start",
        "is_group_end",
        "group_size",
        "record_optimizer_step",
        "on_train_start",
        "configure_train_step",
        "on_optimizer_step_end",
        "state_dict",
        "load_state_dict",
    },
    "torch_batteries.callbacks.GradientClip": {
        "value",
        "algorithm",
        "apply",
        "run_gradient_clip",
        "state_dict",
        "load_state_dict",
    },
    "torch_batteries.callbacks.LearningRateScheduler": {
        "scheduler",
        "interval",
        "on_optimizer_step_end",
        "on_validation_end",
        "on_train_end",
        "state_dict",
        "load_state_dict",
    },
    "torch_batteries.callbacks.MixedPrecision": {
        "precision",
        "effective_precision",
        "scaler",
        "configure",
        "autocast",
        "backward",
        "optimizer_step",
        "unscale_",
        "on_setup",
        "step_execution_context",
        "run_backward",
        "prepare_gradients",
        "run_optimizer_step",
        "state_dict",
        "load_state_dict",
    },
    "torch_batteries.callbacks.ModelCheckpoint": {
        "best_model_path",
        "best_score",
        "best_k_models",
        "state_dict",
        "load_state_dict",
        "run_on_train_epoch_end",
        "run_on_validation_end",
    },
    "torch_batteries.callbacks.TerminateOnNonFinite": {
        "on_before_backward",
        "on_step_end",
        "on_phase_end",
        "state_dict",
        "load_state_dict",
    },
    "torch_batteries.data.DataPack": {"resolve", "state_dict", "load_state_dict"},
    "torch_batteries.data.DataPackHandler": {
        "has_handler",
        "call",
        "provide",
        "setup",
        "build_loader",
        "resolve",
    },
    "torch_batteries.data.DatasetBundle": {
        "__post_init__",
        "for_phase",
        "datasets_for_phase",
    },
    "torch_batteries.data.DataLoaderBundle": {
        "__post_init__",
        "for_phase",
        "loaders_for_phase",
    },
    "torch_batteries.events.EventHandler": {
        "has_handler",
        "get_handler",
        "get_handler_info",
        "get_all_events",
        "call",
        "provide",
        "execute",
        "execution_context",
    },
    "torch_batteries.tracking.ExperimentTracker": {
        "init",
        "is_initialized",
        "log_metrics",
        "finish",
        "log_summary",
        "log_model",
    },
    "torch_batteries.tracking.WandbTracker": {
        "project",
        "entity",
        "run",
        "run_id",
        "run_url",
        "is_initialized",
        "init",
        "log_metrics",
        "finish",
        "log_summary",
        "log_model",
    },
    "torch_batteries.utils.metrics.StatefulMetric": {"reset", "update", "compute"},
    "torch_batteries.utils.metrics.CollectedMetric": {
        "reset",
        "update",
        "compute",
        "compute_collected",
    },
    "torch_batteries.utils.metrics.PhaseMetricManager": {
        "reset",
        "update",
        "compute",
        "state_dict",
        "load_state_dict",
    },
}

# Parameters listed here are compatibility requirements; additive optional parameters
# remain allowed. Values are their current defaults as exposed by inspect.signature.
PUBLIC_PARAMETERS: dict[str, dict[str, object]] = {
    "torch_batteries.callbacks.TerminateOnNonFinite": {
        "check_loss": True,
        "check_metrics": True,
    },
    "torch_batteries.trainer.Battery": {
        "device": "auto",
        "optimizer": None,
        "metrics": None,
        "callbacks": None,
        "data_pack": None,
        "metric_error_policy": "raise",
    },
    "torch_batteries.trainer.Battery.train": {
        "train_loader": None,
        "epochs": 1,
        "verbose": 1,
        "resume_from": None,
        "resume_epochs_mode": "total",
    },
    "torch_batteries.trainer.Battery.fit": {
        "train_loader": None,
        "val_loader": None,
        "epochs": 1,
        "verbose": 1,
        "resume_from": None,
        "resume_epochs_mode": "total",
    },
    "torch_batteries.trainer.Battery.validate": {"val_loader": None, "verbose": 1},
    "torch_batteries.trainer.Battery.test": {
        "test_loader": None,
        "verbose": 1,
        "dataset": None,
    },
    "torch_batteries.trainer.Battery.predict": {
        "data_loader": None,
        "verbose": 1,
        "move_to_cpu": False,
        "concatenate": False,
        "dataset": None,
    },
    "torch_batteries.trainer.Battery.predict_iter": {
        "data_loader": None,
        "verbose": 1,
        "move_to_cpu": False,
        "dataset": None,
    },
}

PUBLIC_KEYWORD_ONLY_PARAMETERS: dict[str, set[str]] = {
    "torch_batteries.callbacks.TerminateOnNonFinite": {
        "check_loss",
        "check_metrics",
    },
    "torch_batteries.trainer.Battery": {"data_pack", "metric_error_policy"},
    "torch_batteries.trainer.Battery.train": {
        "resume_from",
        "resume_epochs_mode",
    },
    "torch_batteries.trainer.Battery.fit": {
        "resume_from",
        "resume_epochs_mode",
    },
    "torch_batteries.trainer.Battery.test": {"dataset"},
    "torch_batteries.trainer.Battery.predict": {
        "move_to_cpu",
        "concatenate",
        "dataset",
    },
    "torch_batteries.trainer.Battery.predict_iter": {"move_to_cpu", "dataset"},
}


REFERENCE_PAGES: dict[str, str] = {
    "torch_batteries.trainer": "reference/trainer/index.html",
    "torch_batteries.callbacks": "reference/callbacks/index.html",
    "torch_batteries.data": "reference/data/index.html",
    "torch_batteries.events": "reference/events/index.html",
    "torch_batteries.tracking": "reference/tracking/index.html",
    "torch_batteries.utils.metrics": "reference/metrics/index.html",
}

# Mkdocstrings does not render typing aliases as addressable HTML endpoints.
REFERENCE_EXCLUSIONS = {
    "torch_batteries.utils.metrics.Metric",
    "torch_batteries.utils.metrics.MetricCallable",
}
